package top.niunaijun.obfuscator;

public class ObfDic {
    public static String[] dic = (
            "ciao\n"+
            "buongiorno\n"+
            "buonasera\n"+
            "arrivederci\n"+
            "perfavore\n"+
            "grazie\n"+
            "prego\n"+
            "scusa\n"+
            "parli \n"+
            "inglese\n"+
            "noncapisco\n"+
            "midispiace\n"+
            "quantocosta\n"+
            "possoavere \n"+
            "ilmenu \n"+
            "perfavore\n"+
            "contoper \n"+
            "favore\n"+
            "bellissimo\n"+
            "caro\n"+
            "buono\n"+
            "cattivo\n"+
            "grande\n"+
            "piccolo\n"+
            "alto\n"+
            "basso\n"+
            "lieto\n"+
            "triste\n"+
            "forte\n"+
            "piano\n"+
            "freddo\n"+
            "caldo\n"+
            "gustoso\n"+
            "amaro\n"+
            "dolce\n"+
            "salute\n"+
            "maiale\n"+
            "carne\n"+
            "pesce\n"+
            "pomodoro\n"+
            "patata\n"+
            "birra\n"+
            "vino\n"+
            "caffè\n"+
            "latte\n"+
            "panino\n"+
            "insalata\n"+
            "frittata\n"+
            "torta\n"+
            "gelato\n"+
            "macchiato\n"+
            "cappuccino\n"+
            "espresso\n"+
            "tiramisu\n"+
            "cannoli\n"+
            "margherita\n"+
            "bruschetta\n"+
            "spaghetti\n"+
            "carbonara\n"+
            "amatriciana\n"+
            "pizza \n"+
            "margherita\n"+
            "fettuccine \n"+
            "alfredo\n"+
            "osso bucco\n"+
            "saltimbocca\n"+
            "arrosto \n"+
            "dimaiale\n"+
            "fegatoal\n"+
            "laveneziana\n"+
            "trippaalla \n"+
            "romana\n"+
            "codaalla \n"+
            "vaccinara\n"+
            "lampredotto\n"+
            "supplì\n"+
            "crostini \n"+
            "difegato\n"+
            "carciofi \n"+
            "allagiudia\n"+
            "peperoni \n"+
            "allaglioe \n"+
            "olio\n"+
            "insalata \n"+
            "caprese\n"+
            "antipasto \n"+
            "misto\n"+
            "minestra \n"+
            "maritata\n"+
            "zuppa \n"+
            "dipesce\n"+
            "ribollita\n"+
            "pappardelle \n"+
            "alcinghiale\n"+
            "gricia\n"+
            "conabbacchio\n"+
            "cacio \n"+
            "epepe\n"+
            "polenta \n"+
            "taragnare \n"+
            "ebrasato \n"+
            "albarolo\n"+
            "farfalle\n"+
            "alla\n"+
            "chitarra\n"+
            "con\n"+
            "ifunghi\n"+
            "porcini\n"+
            "etartufo\n"+
            "nero\n"+
            "della\n"+
            "montagna\n"+
            "della\n"+
            "valle\n"+
            "Aosta\n"+
            "Milano\n"+
            "Roma\n"+
            "Napoli\n"+
            "Torino\n"+
            "Firenze\n"+
            "Venezia\n"+
            "Palermo\n"+
            "Genova\n"+
            "Bologna\n"+
            "Perugia\n"+
            "Modena\n"+
            "Ferrara\n"+
            "Rimini\n"+
            "Padova\n"+
            "Verona\n"+
            "Treviso\n"+
            "Vicenza\n"+
            "Belluno\n"+
            "Trento\n"+
            "Bolzano\n"+
            "Brescia\n"+
            "Parma\n"+
            "Piacenza\n"+
            "Reggio \n"+
            "Emilia\n"+
            "Pesaroe \n"+
            "Urbino\n"+
            "Riminie \n"+
            "SanMarino\n"+
            "Arezzo\n"+
            "Pistoia\n"+
            "Fano\n"+
            "Massa \n"+
            "Marittima\n"+
            "Montecatini \n"+
            "Terme\n"+
            "Varese\n"+
            "Como\n"+
            "Cremona\n"+
            "Lecco\n"+
            "Lodi\n"+
            "Mantova\n"+
            "Pavia\n"+
            "Sondrio\n"+
            "Pesaroe \n"+
            "Urbino \n"+
            "Marittima\n"+
            "LaSpeziae \n"+
            "Porto \n"+
            "Venere\n"+
            "Trapanie \n"+
            "Marsala\n"+
            "Canto\n"+
            "I\n"+
            "del\n"+
            "Purgatorio\n"+
            "apre\n"+
            "la\n"+
            "seconda\n"+
            "Cantica\n"+
            "e\n"+
            "le\n"+
            "porte\n"+
            "al\n"+
            "viaggio\n"+
            "di\n"+
            "Dante\n"+
            "nel\n"+
            "secondo\n"+
            "dei\n"+
            "regni\n"+
            "ultraterreni\n"+
            "Al\n"+
            "verso\n"+
            "troviamo\n"+
            "il\n"+
            "verbo\n"+
            "che\n"+
            "riassume\n"+
            "sinteticamen\n"+
            "quel\n"+
            "che\n"+
            "sarà\n"+
            "largomento\n"+
            "dellintero\n"+
            "Canto\n"+
            "del\n"+
            "Purgatorio\n"+
            "la\n"+
            "risurrezione\n"+
            "delle\n"+
            "anime\n"+
            "ovvero\n"+
            "il\n"+
            "loro\n"+
            "percorso\n"+
            "di\n"+
            "purificazion\n"+
            "e\n"+
            "di\n"+
            "espiazione\n"+
            "dei\n"+
            "propri\n"+
            "peccati\n"+
            "con\n"+
            "il\n"+
            "fine\n"+
            "di\n"+
            "ottenere\n"+
            "la\n"+
            "salvezza\n"+
            "e\n"+
            "di\n"+
            "ascendere\n"+
            "così\n"+
            "al\n"+
            "Paradiso\n"+
            "Un\n"+
            "intento\n"+
            "richiamato\n"+
            "anche\n"+
            "dallambienta\n"
            "spazio-tempo\n"
            "di\n"+
            "questo\n"+
            "primo\n"+
            "Canto\n"+
            "del\n"+
            "Purgatorio\n"+
            "è\n"+
            "la\n"+
            "domenica\n"+
            "di\n"+
            "Pasqua\n"+
            "giorno\n"+
            "in\n"+
            "cui\n"+
            "i\n"+
            "cristiani\n"+
            "festeggiano\n"+
            "la\n"+
            "risurrezione\n"+
            "di\n"+
            "Cristo\n"+
            "e\n"+
            "la\n"+
            "spiaggia\n"+
            "dove\n"+
            "si\n"+
            "trovano\n"+
            "Dante\n"+
            "e\n"+
            "Virgilio\n"+
            "è\n"+
            "avvolta\n"+
            "dalla\n"+
            "luminosità\n"+
            "dellalba\n"+
            "allegoria\n"+
            "della\n"+
            "luce\n"+
            "della\n"+
            "Grazia\n"+
            "divina\n"+
            "che\n"+
            "abbraccia\n"+
            "le\n"+
            "anime\n"+
            "del\n"+
            "Purgatorio\n"+
            "salve\n"+
            "dalla\n"+
            "dannazione\n"+
            "eterna\n"+
            "nonché\n"+
            "simbolo\n"+
            "della\n"+
            "speranza\n"+
            "ritrovata\n"+
            "dopo\n"+
            "le\n"+
            "tenebre\n"+
            "infernali\n"+
            "primo\n"+
            "canto\n"+
            "del\n"+
            "Purgatorio\n"+
            "è\n"+
            "cruciale\n"+
            "perché\n"+
            "segna\n"+
            "la\n"+
            "transizione\n"+
            "di\n"+
            "Dante\n"+
            "da\n"+
            "un\n"+
            "regno\n"+
            "di\n"+
            "disperazione\n"+
            "a\n"+
            "uno\n"+
            "di\n"+
            "speranza\n"+
            "simbolizzato\n"+
            "dallascesa\n"+
            "dallInferno\n"+
            "al\n"+
            "Purgatorio\n"+
            "Introduce\n"+
            "il\n"+
            "concetto\n"+
            "di\n"+
            "pentimento\n"+
            "con\n"+
            "le\n"+
            "anime\n"+
            "pronte\n"+
            "a\n"+
            "purificarsi\n"+
            "dai\n"+
            "loro\n"+
            "peccati\n"+
            "Ci\n"+
            "troviamo\n"+
            "quindi\n"+
            "di\n"+
            "fronte\n"+
            "a\n"+
            "un\n"+
            "ambiente\n"+
            "rasserenato\n"+
            "e\n"+
            "colmo\n"+
            "di\n"+
            "fiducia\n"+
            "ne\n"+
            "consegue\n"+
            "un\n"+
            "innalzamento\n"+
            "dello\n"+
            "stile\n"+
            "che\n"+
            "accompagnerà\n"+
            "lintera\n"+
            "cantica\n"+
            "Protagonista\n"+
            "del\n"+
            "Canto\n"+
            "I\n"+
            "del\n"+
            "Purgatorio\n"+
            "è\n"+
            "Marco\n"+
            "Porcio\n"+
            "Catone\n"+
            "detto\n"+
            "il\n"+
            "Giovane\n"+
            "o\n"+
            "lUticense\n"+
            "per\n"+
            "distinguerlo\n"+
            "dallomonimo\n"+
            "antenato\n"+
            "Catone\n"+
            "il\n"+
            "Censore\n"+
            "Nato\n"+
            "a\n"+
            "Roma\n"+
            "nel\n"+
            "prese\n"+
            "parte\n"+
            "alla\n"+
            "vita\n"+
            "politica\n"+
            "di\n"+
            "Roma\n"+
            "diventando\n"+
            "prima\n"+
            "questore\n"+
            "poi\n"+
            "tribuno\n"+
            "della\n"+
            "plebe\n"+
            "ed\n"+
            "infine\n"+
            "pretore\n"+
            "nel\n"+
            "Estremo\n"+
            "difensore\n"+
            "delle\n"+
            "libertà\n"+
            "politiche\n"+
            "e\n"+
            "repubblicane\n"+
            "si\n"+
            "oppose\n"+
            "fermamente\n"+
            "al\n"+
            "primo\n"+
            "triumvirato\n"+
            "di\n"+
            "Crasso\n"+
            "Cesare\n"+
            "Pompeo\n"+
            "Quando\n"+
            "però\n"+
            "scoppiò\n"+
            "la\n"+
            "guerra\n"+
            "civile\n"+
            "tra\n"+
            "questi\n"+
            "due\n"+
            "ultimi\n"+
            "si\n"+
            "schierò\n"+
            "dalla\n"+
            "parte\n"+
            "di\n"+
            "Pompeo\n"+
            "riconoscendo\n"+
            "nelle\n"+
            "mire\n"+
            "dittatoriali\n"+
            "di\n"+
            "Cesare\n"+
            "un\n"+
            "aperto\n"+
            "attacco\n"+
            "agli\n"+
            "ideali\n"+
            "repubblicani\n"+
            "per\n"+
            "questo\n"+
            "motivo\n"+
            "dopo\n"+
            "la\n"+
            "sconfitta\n"+
            "di\n"+
            "Pompeo\n"+
            "a\n"+
            "Tapso\n"+
            "nel\n"+
            "Catone\n"+
            "decise\n"+
            "di\n"+
            "togliersi\n"+
            "la\n"+
            "vita\n"+
            "a\n"+
            "Utica\n"+
            "città\n"+
            "africana\n"+
            "a\n"+
            "nord\n"+
            "di\n"+
            "Cartagine\n"+
            "Ricostruita\n"+
            "la\n"+
            "vicenda\n"+
            "di\n"+
            "Catone\n"+
            "lUticense\n"+
            "ci\n"+
            "sorge\n"+
            "immediatamen\n"+
            "una\n"+
            "domanda\n"+
            "perché\n"+
            "Dante\n"+
            "ne\n"+
            "fa\n"+
            "il\n"+
            "custode\n"+
            "del\n"+
            "Purgatorio\n"+
            "regno\n"+
            "nel\n"+
            "quale\n"+
            "le\n"+
            "anime\n"+
            "sono\n"+
            "destinate\n"+
            "a\n"+
            "salvarsi\n"+
            "Pagano\n"+
            "morto\n"+
            "suicida\n"+
            "e\n"+
            "avverso\n"+
            "alla\n"+
            "figura\n"+
            "di\n"+
            "Cesare\n"+
            "e\n"+
            "con\n"+
            "essa\n"+
            "quindi\n"+
            "quella\n"+
            "dellImpero\n"+
            "così\n"+
            "cara\n"+
            "invece\n"+
            "a\n"+
            "Dante\n"+
            "il\n"+
            "personaggio\n"+
            "sembra\n"+
            "essere\n"+
            "in\n"+
            "piena\n"+
            "antitesi\n"+
            "con\n"+
            "i\n"+
            "valori\n"+
            "del\n"+
            "poeta\n"+
            "In\n"+
            "realtà\n"+
            "nel\n"+
            "Medioevo\n"+
            "cristiano\n"+
            "la\n"+
            "figura\n"+
            "di\n"+
            "Catone\n"+
            "era\n"+
            "ricollegata\n"+
            "ad\n"+
            "un\n"+
            "modello\n"+
            "di\n"+
            "vita\n"+
            "austera\n"+
            "e\n"+
            "dignitosa\n"+
            "nonché\n"+
            "di\n"+
            "integrità\n"+
            "di\n"+
            "fortezza\n"+
            "morale\n"+
            "e\n"+
            "di\n"+
            "rifiuto\n"+
            "dei\n"+
            "beni\n"+
            "terreni\n"+
            "tutti\n"+
            "valori\n"+
            "fortemente\n"+
            "cristiani\n"+
            "Il\n"+
            "suo\n"+
            "suicidio\n"+
            "è\n"+
            "secondo\n"+
            "Dante\n"+
            "un\n"+
            "gesto\n"+
            "giustificabi\n"+
            "perché\n"+
            "compiuto\n"+
            "con\n"+
            "il\n"+
            "fine\n"+
            "di\n"+
            "salvaguardar\n"+
            "la\n"+
            "libertà\n"+
            "civile\n"+
            "precorritric\n"+
            "della\n"+
            "libertà\n"+
            "interiore\n"+
            "cui\n"+
            "tutte\n"+
            "le\n"+
            "anime\n"+
            "del\n"+
            "Purgatorio\n"+
            "aspirano\n"+
            "e\n"+
            "necessitano\n"+
            "per\n"+
            "poter\n"+
            "ascendere\n"+
            "al\n"+
            "Paradiso\n"+
            "Allinterno\n"+
            "del\n"+
            "Canto\n"+
            "I\n"+
            "del\n"+
            "Purgatorio\n"+
            "più\n"+
            "in\n"+
            "generale\n"+
            "allinterno\n"+
            "dellopera\n"+
            "di\n"+
            "Dante\n"+
            "Catone\n"+
            "assume\n"+
            "quindi\n"+
            "i\n"+
            "connotati\n"+
            "del\n"+
            "modello\n"+
            "della\n"+
            "perfezione\n"+
            "umana\n"+
            "al\n"+
            "suo\n"+
            "più\n"+
            "alto\n"+
            "livello\n"+
            "terreno\n"+
            "che\n"+
            "comporta\n"+
            "la\n"+
            "libertà\n"+
            "assoluta\n"+
            "dalle\n"+
            "passioni\n"+
            "e\n"+
            "lanteposizio\n"+
            "del\n"+
            "bene\n"+
            "comune\n"+
            "al\n"+
            "proprio\n"+
            "Per\n"+
            "questo\n"+
            "motivo\n"+
            "Dante\n"+
            "al\n"+
            "verso\n"+
            "predice\n"+
            "al\n"+
            "guardiano\n"+
            "del\n"+
            "Purgatorio\n"+
            "lassunzione\n"+
            "in\n"+
            "Cielo\n"+
            "dopo\n"+
            "il\n"+
            "Giudizio\n"+
            "Universale\n"+
            "trattamento\n"+
            "che\n"+
            "non\n"+
            "ha\n"+
            "riservato\n"+
            "neanche\n"+
            "al\n"+
            "suo\n"+
            "maestro\n"+
            "Virgilio\n"+
            "Dopo\n"+
            "aver\n"+
            "lasciato\n"+
            "il\n"+
            "terribile\n"+
            "mare\n"+
            "dellInferno\n"+
            "Dante\n"+
            "è\n"+
            "pronto\n"+
            "a\n"+
            "cantare\n"+
            "con\n"+
            "più\n"+
            "tranquillità\n"+
            "il\n"+
            "secondo\n"+
            "regno\n"+
            "dellOltretom\n"+
            "il\n"+
            "Purgatorio\n"+
            "nel\n"+
            "quale\n"+
            "lanima\n"+
            "si\n"+
            "purifica\n"+
            "per\n"+
            "poter\n"+
            "accedere\n"+
            "al\n"+
            "Paradiso\n"+
            "Il\n"+
            "poeta\n"+
            "invoca\n"+
            "laiuto\n"+
            "delle\n"+
            "Muse\n"+
            "e\n"+
            "in\n"+
            "particolare\n"+
            "modo\n"+
            "di\n"+
            "Calliope\n"+
            "chiedendole\n"+
            "di\n"+
            "assisterlo\n"+
            "con\n"+
            "lo\n"+
            "stesso\n"+
            "canto\n"+
            "col\n"+
            "quale\n"+
            "sconfisse\n"+
            "le\n"+
            "Piche\n"+
            "Virgilio\n"+
            "allora\n"+
            "fa\n"+
            "inginocchiar\n"+
            "Dante\n"+
            "di\n"+
            "fronte\n"+
            "a\n"+
            "Catone\n"+
            "e\n"+
            "prende\n"+
            "parola\n"+
            "rispondendo\n"+
            "ai\n"+
            "dubbi\n"+
            "dellanima\n"+
            "veneranda\n"+
            "Gli\n"+
            "spiega\n"+
            "quindi\n"+
            "che\n"+
            "egli\n"+
            "è\n"+
            "stato\n"+
            "incaricato\n"+
            "da\n"+
            "una\n"+
            "donna\n"+
            "beata\n"+
            "a\n"+
            "soccorrere\n"+
            "Dante\n"+
            "e\n"+
            "a\n"+
            "guidarlo\n"+
            "attraverso\n"+
            "lOltretomba\n"+
            "Aggiunge\n"+
            "inoltre\n"+
            "che\n"+
            "Catone\n"+
            "dovrebbe\n"+
            "gradire\n"+
            "la\n"+
            "sua\n"+
            "venuta\n"+
            "il\n"+
            "poeta\n"+
            "fiorentino\n"+
            "cerca\n"+
            "la\n"+
            "libertà\n"+
            "che\n"+
            "è\n"+
            "qualcosa\n"+
            "di\n"+
            "assai\n"+
            "prezioso\n"+
            "come\n"+
            "sa\n"+
            "bene\n"+
            "chi\n"+
            "per\n"+
            "essa\n"+
            "arriva\n"+
            "a\n"+
            "rinunciare\n"+
            "alla\n"+
            "propria\n"+
            "vita\n"+
            "Conclude\n"+
            "infine\n"+
            "dicendo\n"+
            "che\n"+
            "i\n"+
            "due\n"+
            "sono\n"+
            "svincolati\n"+
            "dalle\n"+
            "leggi\n"+
            "infernali\n"+
            "Virgilio\n"+
            "è\n"+
            "unanima\n"+
            "del\n"+
            "Limbo\n"+
            "Dante\n"+
            "è\n"+
            "un\n"+
            "vivente\n"+
            "e\n"+
            "di\n"+
            "farli\n"+
            "passare\n"+
            "in\n"+
            "nome\n"+
            "di\n"+
            "Marzia\n"+
            "moglie\n"+
            "di\n"+
            "Catone\n"+
            "Luomo\n"+
            "risponde\n"+
            "che\n"+
            "concederà\n"+
            "loro\n"+
            "il\n"+
            "passaggio\n"+
            "non\n"+
            "per\n"+
            "Marzia\n"+
            "ma\n"+
            "grazie\n"+
            "alla\n"+
            "donna\n"+
            "del\n"+
            "cielo\n"+
            "che\n"+
            "li\n"+
            "ha\n"+
            "messi\n"+
            "in\n"+
            "viaggio\n"+
            "prima\n"+
            "però\n"+
            "Virgilio\n"+
            "dovrà\n"+
            "lavare\n"+
            "il\n"+
            "volto\n"+
            "di\n"+
            "Dante\n"+
            "e\n"+
            "cingere\n"+
            "la\n"+
            "sua\n"+
            "vita\n"+
            "con\n"+
            "un\n"+
            "giunco\n"+
            "In\n"+
            "particolar\n"+
            "modo\n"+
            "Dante\n"+
            "decide\n"+
            "di\n"+
            "iniziare\n"+
            "la\n"+
            "seconda\n"+
            "cantica\n"+
            "della\n"+
            "Commedia\n"+
            "con\n"+
            "uninvocazion\n"+
            "a\n"+
            "Calliope\n"+
            "musa\n"+
            "protettrice\n"+
            "della\n"+
            "poesia\n"+
            "epica\n"+
            "che\n"+
            "era\n"+
            "stata\n"+
            "invocata\n"+
            "anche\n"+
            "da\n"+
            "Virgilio\n"+
            "nel\n"+
            "Libro\n"+
            "IX\n"+
            "dellEneide\n"+
            "Attraverso\n"+
            "questa\n"+
            "figura\n"+
            "Dante\n"+
            "può\n"+
            "rievocare\n"+
            "il\n"+
            "mito\n"+
            "delle\n"+
            "figlie\n"+
            "di\n"+
            "Pierio\n"+
            "il\n"+
            "re\n"+
            "di\n"+
            "Tessaglia\n"+
            "o\n"+
            "di\n"+
            "Macedonia\n"+
            "Esse\n"+
            "secondo\n"+
            "la\n"+
            "mitologia\n"+
            "ebbero\n"+
            "lardire\n"+
            "di\n"+
            "sfidare\n"+
            "le\n"+
            "Muse\n"+
            "in\n"+
            "una\n"+
            "gara\n"+
            "di\n"+
            "canto\n"+
            "e\n"+
            "furono\n"+
            "vinte\n"+
            "proprio\n"+
            "dalla\n"+
            "voce\n"+
            "melodiosa\n"+
            "di\n"+
            "Calliope\n"+
            "che\n"+
            "per\n"+
            "punirle\n"+
            "le\n"+
            "trasformò\n"+
            "in\n"+
            "piche\n"+
            "cioè\n"+
            "in\n"+
            "gazze\n"+
            "dal\n"+
            "gracchiare\n"+
            "stridulo\n"+
            "In\n"+
            "questo\n"+
            "modo\n"+
            "il\n"+
            "poeta\n"+
            "pone\n"+
            "il\n"+
            "Canto\n"+
            "I\n"+
            "del\n"+
            "Purgatorio\n"+
            "e\n"+
            "con\n"+
            "esso\n"+
            "lintera\n"+
            "cantica \n"+
            "sotto\n"+
            "lammonimento\n"+
            "nei\n"+
            "confronti\n"+
            "della\n"+
            "superbia\n"+
            "Senza\n"+
            "lumiltà\n"+
            "infatti\n"+
            "non\n"+
            "potrebbe\n"+
            "compiersi\n"+
            "la\n"+
            "salvezza\n"+
            "delle\n"+
            "anime\n"+
            "fine\n"+
            "ultimo\n"+
            "del\n"+
            "secondo\n"+
            "regno\n"+
            "ultraterreno\n"+
            "Una\n"+
            "lingua\n"+
            "si\n"+
            "apprende\n"+
            "bene\n"+
            "seguendo\n"+
            "con\n"+
            "pazienza\n"+
            "tutte\n"+
            "le\n"+
            "lezioni\n"+
            "e\n"+
            "non\n"+
            "arrendendosi\n"+
            "davanti\n"+
            "alle\n"+
            "prime\n"+
            "difficoltà\n"+
            "Molto\n"+
            "utile\n"+
            "risulta\n"+
            "la\n"+
            "lettura\n"+
            "sotto\n"+
            "la\n"+
            "guida\n"+
            "dellinsegnan\n"+
            "impadronirsi\n"+
            "della\n"+
            "corretta\n"+
            "pronuncia\n"+
            "I\n"+
            "più\n"+
            "diligenti\n"+
            "potranno\n"+
            "anche\n"+
            "cominciare\n"+
            "a\n"+
            "tradurre\n"+
            "qualche\n"+
            "parola\n"+
            "nella\n"+
            "propria\n"+
            "lingua\n"+
            "e\n"+
            "a\n"+
            "tenere\n"+
            "una\n"+
            "rubrica\n"+
            "in\n"+
            "modo\n"+
            "da\n"+
            "crearsi\n"+
            "un\n"+
            "piccolo\n"+
            "dizionario\n"+
            "personale\n"+
            "Questo\n"+
            "sistema\n"+
            "aiuterà\n"+
            "a\n"+
            "costituire\n"+
            "un\n"+
            "primo\n"+
            "nucleo\n"+
            "di\n"+
            "parole\n"+
            "che\n"+
            "serviranno\n"+
            "in\n"+
            "seguito\n"+
            "per\n"+
            "la\n"+
            "formazione\n"+
            "di\n"+
            "qualche\n"+
            "frase\n"+
            "e\n"+
            "per\n"+
            "unelementare\n"+
            "conversazion\n"+
            "Una\n"+
            "buona\n"+
            "conoscenza\n"+
            "della\n"+
            "lingua\n"+
            "si\n"+
            "avrà\n"+
            "quando\n"+
            "insieme\n"+
            "con\n"+
            "le\n"+
            "norme\n"+
            "grammaticali\n"+
            "si\n"+
            "saranno\n"+
            "apprese\n"+
            "le\n"+
            "norme\n"+
            "pratiche\n"+
            "della\n"+
            "conversazion\n"+
            "che\n"+
            "permetterann\n"+
            "di\n"+
            "esprimersi\n"+
            "chiaramente\n"+
            "nella\n"+
            "nuova\n"+
            "lingua\n"+
            "La\n"+
            "gente\n"+
            "antica\n"+
            "le\n"+
            "vedeva\n"+
            "e\n"+
            "riconosceva\n"+
            "per\n"+
            "quello\n"+
            "che\n"+
            "realmente\n"+
            "sono\n"+
            "grandi\n"+
            "piccole\n"+
            "Divine\n"+
            "navi\n"+
            "dello\n"+
            "spazio\n"+
            "Dallastronav\n"+
            "che\n"+
            "per\n"+
            "evitare\n"+
            "di\n"+
            "nuocere\n"+
            "alle\n"+
            "strutture\n"+
            "energetiche\n"+
            "terrestri\n"+
            "di\n"+
            "minore\n"+
            "potenziale\n"+
            "resta\n"+
            "ancorata\n"+
            "nello\n"+
            "spazio\n"+
            "usano\n"+
            "spesso\n"+
            "uscire\n"+
            "i\n"+
            "dischi\n"+
            "volanti\n"+
            "in\n"+
            "numero\n"+
            "di\n"+
            "quattro\n"+
            "A\n"+
            "tale\n"+
            "proposito\n"+
            "a\n"+
            "pag\n"+
            "del\n"+
            "volume\n"+
            "ANGELI\n"+
            "IN\n"+
            "ASTRONAVE\n"+
            "Ediz\n"+
            "Mediterranée\n"+
            "è\n"+
            "riportato\n"+
            "un\n"+
            "che\n"+
            "mostra\n"+
            "unastronave\n"+
            "e\n"+
            "quattro\n"+
            "dischi\n"+
            "così\n"+
            "come\n"+
            "li\n"+
            "ha\n"+
            "visti\n"+
            "il\n"+
            "testimone\n"+
            "Sono\n"+
            "come\n"+
            "quelle\n"+
            "raffigurate\n"+
            "le\n"+
            "quattro\n"+
            "stelle\n"+
            "di\n"+
            "cui\n"+
            "parla\n"+
            "Dante\n"+
            "Oggi\n"+
            "si\n"+
            "parla\n"+
            "di\n"+
            "Dischi\n"+
            "Volanti\n"+
            "e\n"+
            "di\n"+
            "Astronavi\n"+
            "ma\n"+
            "nessuna\n"+
            "delle\n"+
            "due\n"+
            "realtà\n"+
            "esclude\n"+
            "laltra\n"+
            "anzi\n"+
            "ne\n"+
            "fornisce\n"+
            "una\n"+
            "sintesi\n"+
            "rapportata\n"+
            "in\n"+
            "chiave\n"+
            "religioso-scientifica\n"+
            "e\n"+
            "scientifico-religiosa\n"+
            "E\n"+
            "mentre\n"+
            "i\n"+
            "nostri\n"+
            "Fratelli\n"+
            "del\n"+
            "Cielo\n"+
            "sono\n"+
            "dappertutto\n"+
            "e\n"+
            "in\n"+
            "vari\n"+
            "modi\n"+
            "sulla\n"+
            "Terra\n"+
            "e\n"+
            "vicinissimi\n"+
            "a\n"+
            "contattisti\n"+
            "e\n"+
            "veggenti\n"+
            "gli\n"+
            "scienziati\n"+
            "stanno\n"+
            "impiegando\n"+
            "enormi\n"+
            "capitali\n"+
            "per\n"+
            "mettersi\n"+
            "in\n"+
            "contatto\n"+
            "con\n"+
            "Loro\n"+
            "nello\n"+
            "spazio\n"+
            "e\n"+
            "molti\n"+
            "si\n"+
            "domandano\n"+
            "ancora\n"+
            "se\n"+
            "questi\n"+
            "esseri\n"+
            "esistono\n"+
            "Ma\n"+
            "quelle\n"+
            "STELLE\n"+
            "quelle\n"+
            "NUVOLE\n"+
            "ARDENTI\n"+
            "quelle\n"+
            "splendenti\n"+
            "UOVA\n"+
            "DORO\n"+
            "del\n"+
            "passato\n"+
            "avevano\n"+
            "a\n"+
            "bordo\n"+
            "i\n"+
            "nostri\n"+
            "padri\n"+
            "i\n"+
            "nostri\n"+
            "antenati\n"+
            "le\n"+
            "Creature\n"+
            "Celesti\n"+
            "e\n"+
            "non\n"+
            "il\n"+
            "Signore\n"+
            "Iddio\n"+
            "puro\n"+
            "Spirito\n"+
            "Creatore\n"+
            "senza\n"+
            "corpo\n"+
            "senza\n"+
            "spazio\n"+
            "senza\n"+
            "tempo\n"+
            "bensì\n"+
            "le\n"+
            "Creature\n"+
            "che\n"+
            "noi\n"+
            "adoriamo\n"+
            "perché\n"+
            "le\n"+
            "riteniamo\n"+
            "in\n"+
            "Cielo\n"+
            "E\n"+
            "così\n"+
            "viene\n"+
            "facile\n"+
            "rispondere\n"+
            "ad\n"+
            "Isaia\n"+
            "il\n"+
            "quale\n"+
            "vedendo\n"+
            "i\n"+
            "dischi\n"+
            "volanti\n"+
            "entrare\n"+
            "ed\n"+
            "uscire\n"+
            "dallastronave-madre\n"+
            "si\n"+
            "chiedeva\n"+
            "Chi\n"+
            "son\n"+
            "costoro\n"+
            "che\n"+
            "volano\n"+
            "come\n"+
            "nuvole\n"+
            "come\n"+
            "colombe\n"+
            "al\n"+
            "loro\n"+
            "Da\n"+
            "qui\n"+
            "si\n"+
            "può\n"+
            "intuire\n"+
            "quanto\n"+
            "sia\n"+
            "indispensabile\n"+
            "il\n"+
            "pervenire\n"+
            "alla\n"+
            "Conoscenza\n"+
            "della\n"+
            "Divina\n"+
            "Verità\n"+
            "per\n"+
            "poter\n"+
            "proseguire\n"+
            "verso\n"+
            "il\n"+
            "Celeste\n"+
            "Traguardo\n"+
            "Ed\n"+
            "ecco\n"+
            "il\n"+
            "criterio\n"+
            "di\n"+
            "separazione\n"+
            "dellerba\n"+
            "buona\n"+
            "dalla\n"+
            "gramigna\n"+
            "dellUmanità\n"+
            "spiritualmente\n"+
            "sana\n"+
            "da\n"+
            "quella\n"+
            "malata\n"+
            "che\n"+
            "sta\n"+
            "avendo\n"+
            "luogo\n"+
            "sulla\n"+
            "Terra\n"+
            "era\n"+
            "che\n"+
            "per\n"+
            "lUmanità\n"+
            "si\n"+
            "approssima\n"+
            "un\n"+
            "certo\n"+
            "profetizzato\n"+
            "tempo\n"+
            "Colui\n"+
            "che\n"+
            "sarà\n"+
            "pervaso\n"+
            "dallo\n"+
            "Spirito\n"+
            "di\n"+
            "Conoscenza\n"+
            "avrà\n"+
            "la\n"+
            "forza\n"+
            "necessaria\n"+
            "per\n"+
            "presentarsi\n"+
            "al\n"+
            "primo\n"+
            "ministro\n"+
            "chè\n"+
            "di\n"+
            "quei\n"+
            "di\n"+
            "paradiso\n"+
            "La\n"+
            "Conoscenza\n"+
            "darà\n"+
            "la\n"+
            "forza\n"+
            "sufficiente\n"+
            "affinché\n"+
            "il\n"+
            "potere\n"+
            "dellenergia\n"+
            "che\n"+
            "viene\n"+
            "per\n"+
            "legge\n"+
            "evolutiva\n"+
            "rinnovata\n"+
            "dallesterno\n"+
            "non\n"+
            "disintegri\n"+
            "la\n"+
            "molecola\n"+
            "e\n"+
            "la\n"+
            "proteina\n"+
            "della\n"+
            "cellula-uomo\n"+
            "ciò\n"+
            "perché\n"+
            "il\n"+
            "suo\n"+
            "proprio\n"+
            "campo\n"+
            "di\n"+
            "forza\n"+
            "si\n"+
            "troverà\n"+
            "ad\n"+
            "un\n"+
            "livello\n"+
            "spirituale\n"+
            "dove\n"+
            "questo\n"+
            "aumento\n"+
            "dellenergia\n"+
            "potrà\n"+
            "essere\n"+
            "accumulato\n"+
            "senza\n"+
            "che\n"+
            "la\n"+
            "cellula\n"+
            "e\n"+
            "la\n"+
            "proteina\n"+
            "siano\n"+
            "notevolmente\n"+
            "disturbate\n"+
            "da\n"+
            "essa\n"+
            "La\n"+
            "sopravvivenz\n"+
            "è\n"+
            "assicurata\n"+
            "quindi\n"+
            "a\n"+
            "coloro\n"+
            "che\n"+
            "per\n"+
            "evoluzione\n"+
            "spirituale\n"+
            "hanno\n"+
            "raggiunto\n"+
            "una\n"+
            "struttura\n"+
            "fisica\n"+
            "e\n"+
            "una\n"+
            "frequenza\n"+
            "psichica\n"+
            "che\n"+
            "si\n"+
            "armonizzano\n"+
            "col\n"+
            "superiore\n"+
            "campo\n"+
            "di\n"+
            "forza\n"+
            "Costoro\n"+
            "diventano\n"+
            "dei\n"+
            "portatori\n"+
            "di\n"+
            "Luce\n"+
            "per\n"+
            "i\n"+
            "loro\n"+
            "simili\n"+
            "sotto\n"+
            "forma\n"+
            "di\n"+
            "energia\n"+
            "mentale\n"+
            "e\n"+
            "di\n"+
            "luce\n"+
            "intensificatrice\n"+
            "Vi\n"+
            "è\n"+
            "da\n"+
            "dire\n"+
            "tra\n"+
            "laltro\n"+
            "che\n"+
            "il\n"+
            "potere\n"+
            "dellenergia\n"+
            "che\n"+
            "viene\n"+
            "dallesterno\n"+
            "produrrà\n"+
            "un\n"+
            "certo\n"+
            "effetto\n"+
            "nei\n"+
            "campi\n"+
            "mentali\n"+
            "umani\n"+
            "ciò\n"+
            "che\n"+
            "è\n"+
            "negativo\n"+
            "diventerà\n"+
            "ancor\n"+
            "più\n"+
            "negativo\n"+
            "e\n"+
            "ciò\n"+
            "che\n"+
            "è\n"+
            "positivo\n"+
            "acquisterà\n"+
            "una\n"+
            "maggiore\n"+
            "sintonia\n"+
            "poiché\n"+
            "il\n"+
            "potere\n"+
            "dellaumento\n"+
            "dellenergia\n"+
            "agirà\n"+
            "per\n"+
            "mezzo\n"+
            "dellenergia\n"+
            "che\n"+
            "è\n"+
            "nelluomo\n"+
            "stesso\n"+
            "Quando\n"+
            "questa\n"+
            "energia\n"+
            "che\n"+
            "è\n"+
            "spirituale\n"+
            "è\n"+
            "in\n"+
            "disordine\n"+
            "con\n"+
            "il\n"+
            "mentale\n"+
            "si\n"+
            "produce\n"+
            "un\n"+
            "cortocircuit\n"+
            "ed\n"+
            "allora\n"+
            "certi\n"+
            "fusibili\n"+
            "saltano\n"+
            "Ecco\n"+
            "che\n"+
            "già\n"+
            "assistiamo\n"+
            "ad\n"+
            "una\n"+
            "esasperazion\n"+
            "della\n"+
            "violenza\n"+
            "e\n"+
            "del\n"+
            "male\n"+
            "in\n"+
            "generale\n"+
            "nonché\n"+
            "ad\n"+
            "un\n"+
            "progressivo\n"+
            "sfaldamento\n"+
            "dei\n"+
            "residui\n"+
            "valori\n"+
            "morali\n"+
            "etici\n"+
            "sociali\n"+
            "religiosi\n"+
            "spirituali\n"+
            "sui\n"+
            "quali\n"+
            "si\n"+
            "struttura\n"+
            "ancora\n"+
            "la\n"+
            "società\n"+
            "umana\n"+
            "Quei\n"+
            "pochi\n"+
            "in\n"+
            "cui\n"+
            "il\n"+
            "campo\n"+
            "di\n"+
            "forza\n"+
            "è\n"+
            "in\n"+
            "sintonia\n"+
            "coi\n"+
            "superiori\n"+
            "valori\n"+
            "del\n"+
            "Campo\n"+
            "di\n"+
            "Forza\n"+
            "Universale\n"+
            "dovranno\n"+
            "faticare\n"+
            "non\n"+
            "poco\n"+
            "per\n"+
            "restare\n"+
            "alieni\n"+
            "alle\n"+
            "sollecitazio\n"+
            "negative\n"+
            "espresse\n"+
            "dalla\n"+
            "massa\n"+
            "umana\n"+
            "presa\n"+
            "nel\n"+
            "possente\n"+
            "vortice\n"+
            "di\n"+
            "un\n"+
            "delirio\n"+
            "distruttivo\n"+
            "incontrollab\n"+
            "e\n"+
            "inarrestabil\n"+
            "Ed\n"+
            "ecco\n"+
            "che\n"+
            "a\n"+
            "tale\n"+
            "proposito\n"+
            "nel\n"+
            "seguente\n"+
            "Canto\n"+
            "II\n"+
            "-\n"+
            "v\n"+
            "7-9\n"+
            "si\n"+
            "dirà\n"+
            "che\n"+
            "le\n"+
            "bianche\n"+
            "e\n"+
            "le\n"+
            "vermiglie\n"+
            "guance\n"+
            "de\n"+
            "la\n"+
            "bella\n"+
            "Aurora\n"+
            "per\n"+
            "troppa\n"+
            "etate\n"+
            "divenivan\n"+
            "rance\n"+
            "Da\n"+
            "questa\n"+
            "necessità\n"+
            "scaturisce\n"+
            "la\n"+
            "fraterna\n"+
            "opera\n"+
            "di\n"+
            "aiuto\n"+
            "degli\n"+
            "Extraterrest\n"+
            "che\n"+
            "attraverso\n"+
            "i\n"+
            "messaggi\n"+
            "di\n"+
            "Amore\n"+
            "e\n"+
            "Saggezza\n"+
            "cercano\n"+
            "di\n"+
            "illuminare\n"+
            "la\n"+
            "mente\n"+
            "dellumanità\n"+
            "incosciente\n"+
            "affinché\n"+
            "essa\n"+
            "possa\n"+
            "raggiungere\n"+
            "quella\n"+
            "Forza\n"+
            "Dimensionale\n"+
            "che\n"+
            "aiuta\n"+
            "a\n"+
            "proseguire\n"+
            "verso\n"+
            "il\n"+
            "Regno\n"+
            "di\n"+
            "Dio\n"+
            "Per\n"+
            "correr\n"+
            "miglior\n"+
            "acque\n"+
            "alza\n"+
            "le\n"+
            "vele\n"+
            "omai\n"+
            "la\n"+
            "navicella\n"+
            "del\n"+
            "mio\n"+
            "ingegno\n"+
            "che\n"+
            "lascia\n"+
            "dietro\n"+
            "a\n"+
            "sé\n"+
            "mar\n"+
            "sì\n"+
            "crudele\n"+
            "e\n"+
            "canterò\n"+
            "di\n"+
            "quel\n"+
            "secondo\n"+
            "regno\n"+
            "dove\n"+
            "lumano\n"+
            "spirito\n"+
            "si\n"+
            "purga\n"+
            "e\n"+
            "di\n"+
            "salire\n"+
            "al\n"+
            "ciel\n"+
            "diventa\n"+
            "degno\n"+
            "Ma\n"+
            "qui\n"+
            "la\n"+
            "morta\n"+
            "poesì\n"+
            "resurga\n"+
            "o\n"+
            "sante\n"+
            "Muse\n"+
            "poi\n"+
            "che\n"+
            "vostro\n"+
            "sono\n"+
            "e\n"+
            "qui\n"+
            "Caliopè\n"+
            "alquanto\n"+
            "surga\n"+
            "seguitando\n"+
            "il\n"+
            "mio\n"+
            "canto\n"+
            "con\n"+
            "quel\n"+
            "suono\n"+
            "di\n"+
            "cui\n"+
            "le\n"+
            "Piche\n"+
            "miser\n"+
            "sentiro\n"+
            "lo\n"+
            "colpo\n"+
            "tal\n"+
            "che\n"+
            "disperar\n"+
            "perdono\n"+
            "Dolce\n"+
            "color\n"+
            "doriental\n"+
            "zaffiro\n"+
            "che\n"+
            "saccoglieva\n"+
            "nel\n"+
            "sereno\n"+
            "aspetto\n"+
            "del\n"+
            "mezzo\n"+
            "puro\n"+
            "infino\n"+
            "al\n"+
            "primo\n"+
            "giro\n"+
            "a\n"+
            "li\n"+
            "occhi\n"+
            "miei\n"+
            "ricominciò\n"+
            "diletto\n"+
            "tosto\n"+
            "chio\n"+
            "usci\n"+
            "fuor\n"+
            "de\n"+
            "laura\n"+
            "morta\n"+
            "che\n"+
            "mavea\n"+
            "contristati\n"+
            "li\n"+
            "occhi\n"+
            "e\n"+
            "l\n"+
            "petto\n"+
            "Lo\n"+
            "bel\n"+
            "pianeto\n"+
            "che\n"+
            "damar\n"+
            "conforta\n"+
            "faceva\n"+
            "tutto\n"+
            "rider\n"+
            "loriente\n"+
            "velando\n"+
            "i\n"+
            "Pesci\n"+
            "cherano\n"+
            "in\n"+
            "sua\n"+
            "scorta\n"+
            "I\n"+
            "mi\n"+
            "volsi\n"+
            "a\n"+
            "man\n"+
            "destra\n"+
            "e\n"+
            "puosi\n"+
            "mente\n"+
            "a\n"+
            "laltro\n"+
            "polo\n"+
            "e\n"+
            "vidi\n"+
            "quattro\n"+
            "stelle\n"+
            "non\n"+
            "viste\n"+
            "mai\n"+
            "fuor\n"+
            "cha\n"+
            "la\n"+
            "prima\n"+
            "gente\n"+
            "Goder\n"+
            "pareva\n"+
            "l\n"+
            "ciel\n"+
            "di\n"+
            "lor\n"+
            "fiammelle:\n"+
            "oh\n"+
            "settentriona\n"+
            "vedovo\n"+
            "sito\n"+
            "poi\n"+
            "che\n"+
            "privato\n"+
            "se\n"+
            "di\n"+
            "mirar\n"+
            "quelle\n"+
            "Com\n"+
            "io\n"+
            "da\n"+
            "loro\n"+
            "sguardo\n"+
            "fui\n"+
            "partito\n"+
            "un\n"+
            "poco\n"+
            "me\n"+
            "volgendo\n"+
            "a\n"+
            "laltro\n"+
            "polo\n"+
            "là\n"+
            "onde\n"+
            "l\n"+
            "Carro\n"+
            "già\n"+
            "era\n"+
            "sparito\n"+
            "vidi\n"+
            "presso\n"+
            "di\n"+
            "me\n"+
            "un\n"+
            "veglio\n"+
            "solo\n"+
            "degno\n"+
            "di\n"+
            "tanta\n"+
            "reverenza\n"+
            "in\n"+
            "vista\n"+
            "che\n"+
            "più\n"+
            "non\n"+
            "dee\n"+
            "a\n"+
            "padre\n"+
            "alcun\n"+
            "figliuolo\n"+
            "Lunga\n"+
            "la\n"+
            "barba\n"+
            "e\n"+
            "di\n"+
            "pel\n"+
            "bianco\n"+
            "mista\n"+
            "portava\n"+
            "a\n"+
            "suoi\n"+
            "capelli\n"+
            "simigliante\n"+
            "de\n"+
            "quai\n"+
            "cadeva\n"+
            "al\n"+
            "petto\n"+
            "doppia\n"+
            "lista\n"+
            "Li\n"+
            "raggi\n"+
            "de\n"+
            "le\n"+
            "quattro\n"+
            "luci\n"+
            "sante\n"+
            "fregiavan\n"+
            "sì\n"+
            "la\n"+
            "sua\n"+
            "faccia\n"+
            "di\n"+
            "lume\n"+
            "chi\n"+
            "l\n"+
            "vedea\n"+
            "come\n"+
            "l\n"+
            "sol\n"+
            "fosse\n"+
            "davante\n"+
            "Chi\n"+
            "siete\n"+
            "voi\n"+
            "che\n"+
            "contro\n"+
            "al\n"+
            "cieco\n"+
            "fiume\n"+
            "fuggita\n"+
            "avete\n"+
            "la\n"+
            "pregione\n"+
            "etterna\n"+
            "diss\n"+
            "el\n"+
            "movendo\n"+
            "quelle\n"+
            "oneste\n"+
            "piume\n"+
            "Chi\n"+
            "vha\n"+
            "guidati\n"+
            "o\n"+
            "che\n"+
            "vi\n"+
            "fu\n"+
            "lucerna\n"+
            "uscendo\n"+
            "fuor\n"+
            "de\n"+
            "la\n"+
            "profonda\n"+
            "notte\n"+
            "che\n"+
            "sempre\n"+
            "nera\n"+
            "fa\n"+
            "la\n"+
            "valle\n"+
            "inferna\n"+
            "Son\n"+
            "le\n"+
            "leggi\n"+
            "dabisso\n"+
            "così\n"+
            "rotte?\n"+
            "o\n"+
            "è\n"+
            "mutato\n"+
            "in\n"+
            "ciel\n"+
            "novo\n"+
            "consiglio\n"+
            "che\n"+
            "dannati\n"+
            "venite\n"+
            "a\n"+
            "le\n"+
            "mie\n"+
            "grotte\n"+
            "Lo\n"+
            "duca\n"+
            "mio\n"+
            "allor\n"+
            "mi\n"+
            "diè\n"+
            "di\n"+
            "piglio\n"+
            "e\n"+
            "con\n"+
            "parole\n"+
            "e\n"+
            "con\n"+
            "mani\n"+
            "e\n"+
            "con\n"+
            "cenni\n"+
            "reverenti\n"+
            "mi\n"+
            "fé\n"+
            "le\n"+
            "gambe\n"+
            "e\n"+
            "l\n"+
            "ciglio\n"+
            "Poscia\n"+
            "rispuose\n"+
            "lui\n"+
            "Da\n"+
            "me\n"+
            "non\n"+
            "venni\n"+
            "donna\n"+
            "scese\n"+
            "del\n"+
            "ciel\n"+
            "per\n"+
            "li\n"+
            "cui\n"+
            "prieghi\n"+
            "de\n"+
            "la\n"+
            "mia\n"+
            "compagnia\n"+
            "costui\n"+
            "sovvenni\n"+
            "Ma\n"+
            "da\n"+
            "chè\n"+
            "tuo\n"+
            "voler\n"+
            "che\n"+
            "più\n"+
            "si\n"+
            "spieghi\n"+
            "di\n"+
            "nostra\n"+
            "condizion\n"+
            "com\n"+
            "ell\n"+
            "è\n"+
            "vera\n"+
            "esser\n"+
            "non\n"+
            "puote\n"+
            "il\n"+
            "mio\n"+
            "che\n"+
            "a\n"+
            "te\n"+
            "si\n"+
            "nieghi\n"+
            "Questi\n"+
            "non\n"+
            "vide\n"+
            "mai\n"+
            "lultima\n"+
            "sera\n"+
            "ma\n"+
            "per\n"+
            "la\n"+
            "sua\n"+
            "follia\n"+
            "le\n"+
            "fu\n"+
            "sì\n"+
            "presso\n"+
            "che\n"+
            "molto\n"+
            "poco\n"+
            "tempo\n"+
            "a\n"+
            "volger\n"+
            "era\n"+
            "Sì\n"+
            "com\n"+
            "io\n"+
            "disse\n"+
            "fui\n"+
            "mandato\n"+
            "ad\n"+
            "esso\n"+
            "per\n"+
            "lui\n"+
            "campare\n"+
            "e\n"+
            "non\n"+
            "lì\n"+
            "era\n"+
            "altra\n"+
            "via\n"+
            "che\n"+
            "questa\n"+
            "per\n"+
            "la\n"+
            "quale\n"+
            "i\n"+
            "mi\n"+
            "son\n"+
            "messo\n"+
            "Mostrata\n"+
            "ho\n"+
            "lui\n"+
            "tutta\n"+
            "la\n"+
            "gente\n"+
            "ria\n"+
            "e\n"+
            "ora\n"+
            "intendo\n"+
            "mostrar\n"+
            "quelli\n"+
            "spirti\n"+
            "che\n"+
            "purgan\n"+
            "sé\n"+
            "sotto\n"+
            "la\n"+
            "tua\n"+
            "balìa\n"+
            "Com\n"+
            "io\n"+
            "lho\n"+
            "tratto\n"+
            "saria\n"+
            "lungo\n"+
            "a\n"+
            "dirti\n"+
            "de\n"+
            "lalto\n"+
            "scende\n"+
            "virtù\n"+
            "che\n"+
            "maiuta\n"+
            "conducerlo\n"+
            "a\n"+
            "vederti\n"+
            "e\n"+
            "a\n"+
            "udirti\n"+
            "Or\n"+
            "ti\n"+
            "piaccia\n"+
            "gradir\n"+
            "la\n"+
            "sua\n"+
            "venuta\n"+
            "libertà\n"+
            "va\n"+
            "cercando\n"+
            "chè\n"+
            "sì\n"+
            "cara\n"+
            "come\n"+
            "sa\n"+
            "chi\n"+
            "per\n"+
            "lei\n"+
            "vita\n"+
            "rifiuta\n"+
            "Tu\n"+
            "l\n"+
            "sai\n"+
            "ché\n"+
            "non\n"+
            "ti\n"+
            "fu\n"+
            "per\n"+
            "lei\n"+
            "amara\n"+
            "in\n"+
            "Utica\n"+
            "la\n"+
            "morte\n"+
            "ove\n"+
            "lasciasti\n"+
            "la\n"+
            "vesta\n"+
            "chal\n"+
            "gran\n"+
            "dì\n"+
            "sarà\n"+
            "sì\n"+
            "chiara\n"+
            "Non\n"+
            "son\n"+
            "li\n"+
            "editti\n"+
            "etterni\n"+
            "per\n"+
            "noi\n"+
            "guasti\n"+
            "ché\n"+
            "questi\n"+
            "vive\n"+
            "e\n"+
            "Minòs\n"+
            "me\n"+
            "non\n"+
            "lega\n"+
            "ma\n"+
            "son\n"+
            "del\n"+
            "cerchio\n"+
            "ove\n"+
            "son\n"+
            "li\n"+
            "occhi\n"+
            "casti\n"+
            "di\n"+
            "Marzia\n"+
            "tua\n"+
            "che\n"+
            "n\n"+
            "vista\n"+
            "ancor\n"+
            "ti\n"+
            "priega\n"+
            "o\n"+
            "santo\n"+
            "petto\n"+
            "che\n"+
            "per\n"+
            "tua\n"+
            "la\n"+
            "tegni\n"+
            "per\n"+
            "lo\n"+
            "suo\n"+
            "amore\n"+
            "adunque\n"+
            "a\n"+
            "noi\n"+
            "ti\n"+
            "piega\n"+
            "Lasciane\n"+
            "andar\n"+
            "per\n"+
            "li\n"+
            "tuoi\n"+
            "sette\n"+
            "regni\n"+
            "grazie\n"+
            "riporterò\n"+
            "di\n"+
            "te\n"+
            "a\n"+
            "lei\n"+
            "se\n"+
            "desser\n"+
            "mentovato\n"+
            "là\n"+
            "giù\n"+
            "degni\n"+
            "Marzia\n"+
            "piacque\n"+
            "tanto\n"+
            "a\n"+
            "li\n"+
            "occhi\n"+
            "miei\n"+
            "mentre\n"+
            "chi\n"+
            "fu\n"+
            "di\n"+
            "là\n"+
            "diss\n"+
            "elli\n"+
            "allora\n"+
            "che\n"+
            "quante\n"+
            "grazie\n"+
            "volse\n"+
            "da\n"+
            "me\n"+
            "fei\n"+
            "Or\n"+
            "che\n"+
            "di\n"+
            "là\n"+
            "dal\n"+
            "mal\n"+
            "fiume\n"+
            "dimora\n"+
            "più\n"+
            "muover\n"+
            "non\n"+
            "mi\n"+
            "può\n"+
            "per\n"+
            "quella\n"+
            "legge\n"+
            "che\n"+
            "fatta\n"+
            "fu\n"+
            "quando\n"+
            "me\n"+
            "nusci\n"+
            "fora\n"+
            "Ma\n"+
            "se\n"+
            "donna\n"+
            "del\n"+
            "ciel\n"+
            "ti\n"+
            "move\n"+
            "e\n"+
            "regge\n"+
            "come\n"+
            "tu\n"+
            "di\n"+
            "non\n"+
            "cè\n"+
            "mestier\n"+
            "lusinghe\n"+
            "bastisi\n"+
            "ben\n"+
            "che\n"+
            "per\n"+
            "lei\n"+
            "mi\n"+
            "richegge\n"+
            "Va\n"+
            "dunque\n"+
            "e\n"+
            "fa\n"+
            "che\n"+
            "tu\n"+
            "costui\n"+
            "ricinghe\n"+
            "dun\n"+
            "giunco\n"+
            "schietto\n"+
            "e\n"+
            "che\n"+
            "li\n"+
            "lavi\n"+
            "l\n"+
            "viso\n"+
            "sì\n"+
            "chogne\n"+
            "sucidume\n"+
            "quindi\n"+
            "stinghe\n"+
            "ché\n"+
            "non\n"+
            "si\n"+
            "converria\n"+
            "locchio\n"+
            "sorpriso\n"+
            "dalcuna\n"+
            "nebbia\n"+
            "andar\n"+
            "dinanzi\n"+
            "al\n"+
            "primo\n"+
            "ministro\n"+
            "chè\n"+
            "di\n"+
            "quei\n"+
            "di\n"+
            "paradiso\n"+
            "Questa\n"+
            "isoletta\n"+
            "intorno\n"+
            "ad\n"+
            "imo\n"+
            "ad\n"+
            "imo\n"+
            "là\n"+
            "giù\n"+
            "colà\n"+
            "dove\n"+
            "la\n"+
            "batte\n"+
            "londa\n"+
            "porta\n"+
            "di\n"+
            "giunchi\n"+
            "sovra\n"+
            "l\n"+
            "molle\n"+
            "limo\n"+
            "null\n"+
            "altra\n"+
            "pianta\n"+
            "che\n"+
            "facesse\n"+
            "fronda\n"+
            "o\n"+
            "indurasse\n"+
            "vi\n"+
            "puote\n"+
            "aver\n"+
            "vita\n"+
            "però\n"+
            "cha\n"+
            "le\n"+
            "percosse\n"+
            "non\n"+
            "seconda\n"+
            "Poscia\n"+
            "non\n"+
            "sia\n"+
            "di\n"+
            "qua\n"+
            "vostra\n"+
            "reddita\n"+
            "lo\n"+
            "sol\n"+
            "vi\n"+
            "mostrerrà\n"+
            "che\n"+
            "sorge\n"+
            "omai\n"+
            "prendere\n"+
            "il\n"+
            "monte\n"+
            "a\n"+
            "più\n"+
            "lieve\n"+
            "salita\n"+
            "Così\n"+
            "sparì\n"+
            "e\n"+
            "io\n"+
            "sù\n"+
            "mi\n"+
            "levai\n"+
            "sanza\n"+
            "parlare\n"+
            "e\n"+
            "tutto\n"+
            "mi\n"+
            "ritrassi\n"+
            "al\n"+
            "duca\n"+
            "mio\n"+
            "e\n"+
            "li\n"+
            "occhi\n"+
            "a\n"+
            "lui\n"+
            "drizzai\n"+
            "El\n"+
            "cominciò\n"+
            "Figliuol\n"+
            "segui\n"+
            "i\n"+
            "miei\n"+
            "passi\n"+
            "volgianci\n"+
            "in\n"+
            "dietro\n"+
            "ché\n"+
            "di\n"+
            "qua\n"+
            "dichina\n"+
            "questa\n"+
            "pianura\n"+
            "a\n"+
            "suoi\n"+
            "termini\n"+
            "bassi\n"+
            "Lalba\n"+
            "vinceva\n"+
            "lora\n"+
            "mattutina\n"+
            "che\n"+
            "fuggia\n"+
            "innanzi\n"+
            "sì\n"+
            "che\n"+
            "di\n"+
            "lontano\n"+
            "conobbi\n"+
            "il\n"+
            "tremolar\n"+
            "de\n"+
            "la\n"+
            "marina\n"+
            "Noi\n"+
            "andavam\n"+
            "per\n"+
            "lo\n"+
            "solingo\n"+
            "piano\n"+
            "com\n"+
            "om\n"+
            "che\n"+
            "torna\n"+
            "a\n"+
            "la\n"+
            "perduta\n"+
            "strada\n"+
            "che\n"+
            "nfino\n"+
            "ad\n"+
            "essa\n"+
            "li\n"+
            "pare\n"+
            "ire\n"+
            "in\n"+
            "vano\n"+
            "Quando\n"+
            "noi\n"+
            "fummo\n"+
            "là\n"+
            "ve\n"+
            "la\n"+
            "rugiada\n"+
            "pugna\n"+
            "col\n"+
            "sole\n"+
            "per\n"+
            "essere\n"+
            "in\n"+
            "parte\n"+
            "dove\n"+
            "ad\n"+
            "orezza\n"+
            "poco\n"+
            "si\n"+
            "dirada\n"+
            "ambo\n"+
            "le\n"+
            "mani\n"+
            "in\n"+
            "su\n"+
            "lerbetta\n"+
            "sparte\n"+
            "soavemente\n"+
            "l\n"+
            "mio\n"+
            "maestro\n"+
            "pose\n"+
            "ond\n"+
            "io\n"+
            "che\n"+
            "fui\n"+
            "accorto\n"+
            "di\n"+
            "sua\n"+
            "arte\n"+
            "porsi\n"+
            "ver\n"+
            "lui\n"+
            "le\n"+
            "guance\n"+
            "lagrimose\n"+
            "ivi\n"+
            "mi\n"+
            "fece\n"+
            "tutto\n"+
            "discoverto\n"+
            "quel\n"+
            "color\n"+
            "che\n"+
            "linferno\n"+
            "mi\n"+
            "nascose\n"+
            "Venimmo\n"+
            "poi\n"+
            "in\n"+
            "sul\n"+
            "lito\n"+
            "diserto\n"+
            "che\n"+
            "mai\n"+
            "non\n"+
            "vide\n"+
            "navicar\n"+
            "sue\n"+
            "acque\n"+
            "omo\n"+
            "che\n"+
            "di\n"+
            "tornar\n"+
            "sia\n"+
            "poscia\n"+
            "esperto\n"+
            "Quivi\n"+
            "mi\n"+
            "cinse\n"+
            "sì\n"+
            "com\n"+
            "altrui\n"+
            "piacque\n"+
            "oh\n"+
            "maraviglia\n"+
            "ch\n"+
            "e\n"+
            "qual\n"+
            "elli\n"+
            "scelse\n"+
            "lumile\n"+
            "pianta\n"+
            "cotal\n"+
            "si\n"+
            "rinacque\n"+
            "subitamente\n"+
            "là\n"+
            "onde\n"+
            "lavelse\n"
           ).split("\n");
            }
            